### ISSUE TITLE
Create search page

### ISSUE THREAD

**Issue by Skagevang** [IT2810/it2810-webutvikling-h17-prosjekt-4-group20#3]
- [x] make search work
- [x] get only 10 movies at a time. get 10 more on scroll
- [x] get pictures, director and rating too
- [x] add to watchlist in modal should add the object to a variable
- [x] sort by title and rating
- [x] filter by genres and year

**Comment by andreajl** [comment]
http://physalix.com/jquery-autocomplete-search-with-node-js-and-mongoose/
